<?php

/**
 * Implements hook_twitter_status_save().
 */
function twitter_archive_twitter_status_save($status) {
  module_load_include('inc', 'twitter');

  $query = db_select('twitter_account')
    ->fields('twitter_account', array('twitter_uid'))
    ->condition('screen_name', $status->user->screen_name)
    ->execute();
  $twitter_uid = $query->fetchField();
  $account = twitter_account_load($twitter_uid);

  $twitter = twitter_connect($account);

  $params = array(
    'id' => $status->id,
    'include_entities' => 'true',
  );
  $status->data = $twitter->call('statuses/show', $params, 'GET', TRUE);

  $query = db_select('twitter_archive', 'ta')
    ->fields('ta', array('id'))
    ->condition('id', $status->id);

  if ($query->execute()->fetchField()) {
    drupal_write_record('twitter_archive', $status, 'id');
  }
  else {
    drupal_write_record('twitter_archive', $status);
  }
}
